import {
  Wrench,
  Fuel,
  Calculator,
  Users,
  UsersRound,
  MapPinned,
  ShieldAlert,
  Bell,
  Tag,
  Store,
  Grid3X3,
  TrendingUp,
  FileText,
  FileStack,
  LayoutDashboard,
  CarFront,
  Layers3,
} from "lucide-react";

/** Moroccan-friendly labels — simple French, short subtitles */
export const GARAGE_FEATURES = [
  {
    id: "mechanic-prices",
    to: "/mechanic-prices",
    fr: "Prix garagiste",
    subtitleFr: "Évitez les devis trop chers",
    en: "Mechanic prices",
    subtitleEn: "Avoid overpriced quotes",
    Icon: Wrench,
    gradient: "linear-gradient(135deg,#f59e0b,#d97706)",
    glow: "rgba(245,158,11,0.35)",
  },
  {
    id: "car-worth",
    to: "/car-worth",
    fr: "Chhal tswa daba?",
    subtitleFr: "Valeur du jour au Maroc",
    en: "Worth today",
    subtitleEn: "Today's value in Morocco",
    Icon: TrendingUp,
    gradient: "linear-gradient(135deg,#10b981,#059669)",
    glow: "rgba(16,185,129,0.35)",
  },
  {
    id: "fuel",
    to: "/fuel-tracker",
    fr: "Carburant",
    subtitleFr: "L/100km & comparaison",
    en: "Fuel",
    subtitleEn: "L/100km & compare",
    Icon: Fuel,
    gradient: "linear-gradient(135deg,#38bdf8,#0284c7)",
    glow: "rgba(56,189,248,0.35)",
  },
  {
    id: "travel",
    to: "/travel-ready",
    fr: "Avant le voyage",
    subtitleFr: "Prêt pour la route?",
    en: "Before travel",
    subtitleEn: "Road-trip ready?",
    Icon: MapPinned,
    gradient: "linear-gradient(135deg,#0ea5e9,#6366f1)",
    glow: "rgba(99,102,241,0.35)",
  },
  {
    id: "community",
    to: "/community",
    fr: "Communauté",
    subtitleFr: "Même voiture que vous",
    en: "Community",
    subtitleEn: "Owners like you",
    Icon: UsersRound,
    gradient: "linear-gradient(135deg,#a855f7,#7c3aed)",
    glow: "rgba(168,85,247,0.35)",
  },
  {
    id: "emergency",
    to: "/emergency",
    fr: "Accident",
    subtitleFr: "Guide urgence Maroc",
    en: "Accident",
    subtitleEn: "Morocco emergency",
    Icon: ShieldAlert,
    gradient: "linear-gradient(135deg,#ef4444,#b91c1c)",
    glow: "rgba(239,68,68,0.4)",
  },
  {
    id: "estimate",
    to: "/estimate",
    fr: "Estimer",
    subtitleFr: "Prix de vente",
    en: "Estimate",
    subtitleEn: "Selling price",
    Icon: Calculator,
    gradient: "linear-gradient(135deg,#6366f1,#4f46e5)",
    glow: "rgba(99,102,241,0.35)",
    action: "estimate",
  },
  {
    id: "sell",
    to: "/my-sales/new",
    fr: "Vendre",
    subtitleFr: "Publier annonce",
    en: "Sell",
    subtitleEn: "List your car",
    Icon: Tag,
    gradient: "linear-gradient(135deg,#c084fc,#a78bfa)",
    glow: "rgba(192,132,252,0.35)",
  },
  {
    id: "alerts",
    to: "/price-alerts",
    fr: "Alertes prix",
    subtitleFr: "Bonne affaire",
    en: "Price alerts",
    subtitleEn: "Good deals",
    Icon: Bell,
    gradient: "linear-gradient(135deg,#22c55e,#16a34a)",
    glow: "rgba(34,197,94,0.35)",
  },
  {
    id: "market",
    to: "/cars",
    fr: "Marché",
    subtitleFr: "Voir les annonces",
    en: "Market",
    subtitleEn: "Browse listings",
    Icon: Store,
    gradient: "linear-gradient(135deg,#f97316,#ea580c)",
    glow: "rgba(249,115,22,0.35)",
  },
  {
    id: "docs",
    to: "/garage/documents",
    fr: "Documents",
    subtitleFr: "Carte grise, assurance…",
    en: "Documents",
    subtitleEn: "Papers & scans",
    Icon: FileStack,
    gradient: "linear-gradient(135deg,#14b8a6,#0d9488)",
    glow: "rgba(20,184,166,0.35)",
  },
  {
    id: "listings",
    to: "/dashboard",
    fr: "Mes annonces",
    subtitleFr: "Gérer ventes",
    en: "My listings",
    subtitleEn: "Manage sales",
    Icon: Grid3X3,
    gradient: "linear-gradient(135deg,#7c6bff,#5b4fc7)",
    glow: "rgba(124,107,255,0.35)",
  },
];

export const GARAGE_TABS = [
  { id: "today", fr: "Accueil", en: "Home", Icon: LayoutDashboard },
  { id: "car", fr: "Ma voiture", en: "My car", Icon: CarFront },
  { id: "tools", fr: "Outils", en: "Tools", Icon: Layers3 },
];
